### ISSUE TITLE
Include Releases

### ISSUE THREAD

**Issue by xIceFox** [thombles/hashgood#1]
Hey first i want to say that tool is awesome.
I wrote one for myself in python and then I found yours, and it is perfect for the job! Probs on that.

But maybe for the not so technical users out there, it maybe would be cool to include releases for the standard plattforms.

I needed like 20 Minutes to compile this, because on Windows you need to install the VisualStudio Build tools to get the rust compiler running, which takes forever.

Keep the amazing work up

**Comment by thombles** [comment]
Thanks for the request! I've cut a version 0.2.0 which is now available for Mac/Windows/Linux under [releases](https://github.com/thombles/hashgood/releases), along with automation through GitHub Actions so it will be easy to keep them coming.
