### ISSUE TITLE
Consider publishing hashgood to crates.io

### ISSUE THREAD

**Issue by ameknite** [thombles/hashgood#3]
This will allow to build from source with:
`cargo install hashgood `

**Comment by thombles** [comment]
This is done. Thanks for the suggestion. https://crates.io/crates/hashgood

I'm convinced that a few years ago I read some policy or at least an attitude that binary crates should be related to developer workflows in some way if they are going to be published on crates.io. However I did some digging and can't find any reason why not to simply publish it, so I have.
